{ pkgs, lib, ... }:

let
  mod = "SUPER"; # Main key of Sway

  terminal = "alacritty msg create-window";
  explorer = "thunar";
  launcher = "fuzzel";

  keyboards = "us,ru,ua";

  screenshot = "grimshot copy screen";
  windowshot = "grimshot copy anything";
in
{
  home.packages = with pkgs; [
    sway-contrib.grimshot
  ];

  stylix.targets.sway.enable = false;

  wayland.windowManager.sway = {
    enable = true;
    xwayland = true;
    checkConfig = false;

    package = pkgs.swayfx;

    config = {
      modifier = mod;

      # Changes the active window based on where is your mouse cursor
      focus.followMouse = true;

      # Allows moving floating windows with Mod + left mouse button
      # and resizing any windows with Mod + right mouse button
      floating.modifier = "${mod} normal";

      input."*" = {
        "xkb_layout" = keyboards;
        "xkb_options" = "grp:caps_toggle";
      };

      gaps = {
        # Make top margin non-existent to better blend in
        # with our gradient Waybar background.
        top = 0;
        bottom = 5;
        left = 5;
        right = 5;
        inner = 5;
      };

      window = {
        titlebar = false;
        border = 2;
      };

      floating.border = 2;

      # Fixes issues when you press Mod + й (russian equivalent of Mod + q)
      # but nothing happens
      bindkeysToCode = true;

      defaultWorkspace = "workspace number 1";

      keybindings = {
        "${mod}+q" = "exec ${terminal}";
        "${mod}+e" = "exec ${explorer}";
        "${mod}+r" = "exec ${launcher}";

        "${mod}+c" = "kill"; # Close the focused window
        "${mod}+m" = "exec swaymsg exit"; # Log out of Sway

        "${mod}+v" = "floating toggle"; # Makes windows float
        "${mod}+j" = "layout toggle split";

        # Those are key codes for the FN media keys.
        # You can find out more of them by using `wev` utility.
        "XF86AudioRaiseVolume" = "exec wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+";
        "XF86AudioLowerVolume" = "exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-";
        "XF86AudioMute" = "exec wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle";
        "XF86AudioMicMute" = "exec wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle";
        "XF86AudioNext" = "exec playerctl next";
        "XF86AudioPause" = "exec playerctl play-pause";
        "XF86AudioPlay" = "exec playerctl play-pause";
        "XF86AudioPrev" = "exec playerctl previous";

        # Mod1 is Alt
        "Print" = "exec ${screenshot}";
        "Mod1+Print" = "exec ${windowshot}";

        "${mod}+1" = "workspace number 1";
        "${mod}+2" = "workspace number 2";
        "${mod}+3" = "workspace number 3";
        "${mod}+4" = "workspace number 4";
        "${mod}+5" = "workspace number 5";
        "${mod}+6" = "workspace number 6";
        "${mod}+7" = "workspace number 7";
        "${mod}+8" = "workspace number 8";
        "${mod}+9" = "workspace number 9";
        "${mod}+0" = "workspace number 10";

        "${mod}+Shift+1" = "move container to workspace number 1";
        "${mod}+Shift+2" = "move container to workspace number 2";
        "${mod}+Shift+3" = "move container to workspace number 3";
        "${mod}+Shift+4" = "move container to workspace number 4";
        "${mod}+Shift+5" = "move container to workspace number 5";
        "${mod}+Shift+6" = "move container to workspace number 6";
        "${mod}+Shift+7" = "move container to workspace number 7";
        "${mod}+Shift+8" = "move container to workspace number 8";
        "${mod}+Shift+9" = "move container to workspace number 9";
        "${mod}+Shift+0" = "move container to workspace number 10";
      };

      # Make those borders white.
      # All other colors are generated by Stylix, and that's
      # why we need to use `lib.mkForce`.
      colors = {
        focused = {
          background = "#18191b";
          border = "#4D4E51";
          childBorder = "#4D4E51";
          indicator = "#4D4E51";
          text = "#e0e1e4";
        };
        focusedInactive = {
          background = "#18191b";
          border = "#4D4E51";
          childBorder = "#4D4E51";
          indicator = "#4D4E51";
          text = "#e0e1e4";
        };
        unfocused = {
          background = "#18191b";
          border = "#4D4E5100";
          childBorder = "#4D4E5100";
          indicator = "#4D4E5100";
          text = "#e0e1e4";
        };
        placeholder = {
          background = "#18191b";
          border = "#4D4E51";
          childBorder = "#4D4E51";
          indicator = "#4D4E51";
          text = "#e0e1e4";
        };
        urgent = {
          background = "#18191b";
          border = "#eb4056";
          childBorder = "#eb4056";
          indicator = "#eb4056";
          text = "#e0e1e4";
        };
      };

      bars = [];
    };

    extraConfig = ''
       default_dim_inactive 0.8
       dim_inactive_colors.unfocused #00000088

       corner_radius 9

       shadows enable
       shadow_color #000000FF
       shadow_inactive_color #00000000

       shadow_offset 0 0
       shadow_blur_radius 20
    '';
  };

  # Screencasting
  xdg.portal = {
    enable = true;
    extraPortals = with pkgs; [ xdg-desktop-portal-wlr lxqt.xdg-desktop-portal-lxqt ];
    xdgOpenUsePortal = true;

    config.common = {
      default = [ "gtk" ];
      "org.freedesktop.impl.portal.FileChooser" = "lxqt";
    };

    # https://github.com/NixOS/nixpkgs/blob/6df2f671f1eca65dce7c78e547b44b0f60ca10de/nixos/modules/programs/wayland/sway.nix
    config.sway = {
      default = [ "gtk" ];
      "org.freedesktop.impl.portal.ScreenCast" = "wlr";
      "org.freedesktop.impl.portal.Screenshot" = "wlr";
      "org.freedesktop.impl.portal.Inhibit" = "none";
    };
  };

}
