{ pkgs, lib, ... }:

let
  mod = "SUPER"; # Main key of Sway

  terminal = "alacritty";
  explorer = "thunar";
  launcher = "fuzzel";

  keyboards = "us,ru,ua";

  # Path to a wallpaper. toString with a relative argument
  # will reference a file in the flake folder. To use another
  # path not in a flake, just replace it with a string, e.g.
  # wallpaper = "/home/sophie/wallpapers/cool-wallpaper.png";
  wallpaper = toString ../wallpapers/v3.png;

  screenshot = "grimshot copy screen";
  windowshot = "grimshot copy window";
in
{
  home.packages = with pkgs; [
    sway-contrib.grimshot
  ];

  # Screencasting
  xdg.portal = {
    enable = true;
    extraPortals = with pkgs; [ xdg-desktop-portal-wlr ];

    # https://github.com/NixOS/nixpkgs/blob/6df2f671f1eca65dce7c78e547b44b0f60ca10de/nixos/modules/programs/wayland/sway.nix
    config.sway = {
      # Use xdg-desktop-portal-gtk for every portal interface...
      default = [ "gtk" ];
      # ... except for the ScreenCast, Screenshot and Secret
      "org.freedesktop.impl.portal.ScreenCast" = "wlr";
      "org.freedesktop.impl.portal.Screenshot" = "wlr";
      # ignore inhibit bc gtk portal always returns as success,
      # despite sway/the wlr portal not having an implementation,
      # stopping firefox from using wayland idle-inhibit
      "org.freedesktop.impl.portal.Inhibit" = "none";
    };
  };

  # stylix.targets.sway.enable = false;

  wayland.windowManager.sway = {
    enable = true;
    xwayland = true;
    checkConfig = false;

    config = {
      modifier = mod;

      # Changes the active window based on where is your mouse cursor
      focus.followMouse = true;

      # Allows moving floating windows with Mod + left mouse button
      # and resizing any windows with Mod + right mouse button
      floating.modifier = "${mod} normal";

      input."*" = {
        "xkb_layout" = keyboards;
        "xkb_options" = "grp:caps_toggle";
      };

      output."*".bg = "${wallpaper} fill";

      gaps = {
        # Make top margin non-existent to better blend in
        # with our gradient Waybar background.
        top = 0;
        bottom = 5;
        left = 5;
        right = 5;
        inner = 5;
      };

      window = {
        titlebar = false;
        border = 1;
      };

      floating.border = 1;

      # Fixes issues when you press Mod + й (russian equivalent of Mod + q)
      # but nothing happens
      bindkeysToCode = true;

      defaultWorkspace = "workspace number 1";

      keybindings = {
        "${mod}+q" = "exec ${terminal}";
        "${mod}+e" = "exec ${explorer}";
        "${mod}+r" = "exec ${launcher}";

        "${mod}+c" = "kill"; # Close the focused window
        "${mod}+m" = "exec swaymsg exit"; # Log out of Sway

        "${mod}+v" = "floating toggle"; # Makes windows float
        "${mod}+j" = "layout toggle split";

        # Those are key codes for the FN media keys.
        # You can find out more of them by using `wev` utility.
        "XF86AudioRaiseVolume" = "exec wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+";
        "XF86AudioLowerVolume" = "exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-";
        "XF86AudioMute" = "exec wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle";
        "XF86AudioMicMute" = "exec wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle";
        "XF86AudioNext" = "exec playerctl next";
        "XF86AudioPause" = "exec playerctl play-pause";
        "XF86AudioPlay" = "exec playerctl play-pause";
        "XF86AudioPrev" = "exec playerctl previous";

        # Mod1 is Alt
        "Print" = "exec ${screenshot}";
        "Mod1+Print" = "exec ${windowshot}";

        "${mod}+1" = "workspace number 1";
        "${mod}+2" = "workspace number 2";
        "${mod}+3" = "workspace number 3";
        "${mod}+4" = "workspace number 4";
        "${mod}+5" = "workspace number 5";
        "${mod}+6" = "workspace number 6";
        "${mod}+7" = "workspace number 7";
        "${mod}+8" = "workspace number 8";
        "${mod}+9" = "workspace number 9";
        "${mod}+0" = "workspace number 10";

        "${mod}+Shift+1" = "move container to workspace number 1";
        "${mod}+Shift+2" = "move container to workspace number 2";
        "${mod}+Shift+3" = "move container to workspace number 3";
        "${mod}+Shift+4" = "move container to workspace number 4";
        "${mod}+Shift+5" = "move container to workspace number 5";
        "${mod}+Shift+6" = "move container to workspace number 6";
        "${mod}+Shift+7" = "move container to workspace number 7";
        "${mod}+Shift+8" = "move container to workspace number 8";
        "${mod}+Shift+9" = "move container to workspace number 9";
        "${mod}+Shift+0" = "move container to workspace number 10";
      };

      # Make those borders white.
      # All other colors are generated by Stylix, and that's
      # why we need to use `lib.mkForce`.
      colors = {
        focused = {
          border = lib.mkForce "#ffffff";
          indicator = lib.mkForce "#ffffff";
        };
        focusedInactive = {
          border = lib.mkForce "#ffffff";
          indicator = lib.mkForce "#ffffff";
        };
        unfocused = {
          border = lib.mkForce "#ffffff00";
          indicator = lib.mkForce "#ffffff00";
        };
        placeholder = {
          border = lib.mkForce "#ffffff";
          indicator = lib.mkForce "#ffffff";
        };
      };

      bars = [];
    };
  };
}
